version: "3"

services:
  api-cycle-finance-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apicyclefinance
    # volumes:
    #   - pg_data:/bitnami/postgresql

  redis:
    image: redis:alpine
    container_name: cycle-redis
    ports:
      - 6379:6379
    # command: redis-server --requirepass xy616F18I
    # volumes:
    #   - redis_data:/data

# volumes:
#   pg_data:
#   redis_data:
